config/routes.rb
Style::Application.routes.draw do

  root :to => 'home#index'

  resources :outfits_pieces
  resources :outfits
  resources :pieces
  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # resources :home
  # get '/about' => 'home#about'
  # get '/faq' => 'home#faq'
  # get '/contact' => 'home#contact'
  # get '/index' => 'home#index'
end

app/models/outfit.rb
# == Schema Information
#
# Table name: outfits
#
#  id         :integer          not null, primary key
#  image      :text
#  name       :string(255)
#  occasion   :string(255)
#  notes      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Outfit < ActiveRecord::Base
  attr_accessible :image, :name, :occasion, :notes, :piece_ids
  has_and_belongs_to_many :pieces
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :email, :password, :password_confirmation
  has_many :pieces, :inverse_of => :user
  has_many :outfits, :inverse_of => :user
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  # GET /outfits
  # GET /outfits.json
  def index
    @outfits = Outfit.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @outfits }
    end
  end

  # GET /outfits/1
  # GET /outfits/1.json
  def show
    @outfit = Outfit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @outfit }
    end
  end

  # GET /outfits/new
  # GET /outfits/new.json
  def new
    @outfit = Outfit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @outfit }
    end
  end

  # GET /outfits/1/edit
  def edit
    @outfit = Outfit.find(params[:id])
  end

  # POST /outfits
  # POST /outfits.json
  def create
    @outfit = Outfit.new(params[:outfit])

    respond_to do |format|
      if @outfit.save
        format.html { redirect_to @outfit, notice: 'Outfit was successfully created.' }
        format.json { render json: @outfit, status: :created, location: @outfit }
      else
        format.html { render action: "new" }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /outfits/1
  # PUT /outfits/1.json
  def update
    @outfit = Outfit.find(params[:id])

    respond_to do |format|
      if @outfit.update_attributes(params[:outfit])
        format.html { redirect_to @outfit, notice: 'Outfit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outfits/1
  # DELETE /outfits/1.json
  def destroy
    @outfit = Outfit.find(params[:id])
    @outfit.destroy

    respond_to do |format|
      format.html { redirect_to outfits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/views/outfits/_form.html.erb
<%= form_for(@outfit) do |f| %>
  <% if @outfit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outfit.errors.count, "error") %> prohibited this outfit from being saved:</h2>

      <ul>
      <% @outfit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, :autofocus => 'autofocus' %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :occasion %>
    <%= f.text_field :occasion %>
    <br>
    <%= f.label :notes %>
    <%= f.text_field :notes %>

<br>
<% Piece.order(:image).each do |piece| %>
  <span><%= image_tag(piece.image, :size => "100x100") %></span>
  <%= check_box_tag 'outfit[piece_ids][]', piece.id, piece.in?(@outfit.pieces) %>
<% end %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outfits/_form.html.haml
.outfits_form
  = form_for(@outfit) do |f|
    - if @outfit.errors.any?
      #error_explanation
        %h2
          = pluralize(@outfit.errors.count, "error")
          prohibited this outfit from being saved:
        %ul
          - @outfit.errors.full_messages.each do |msg|
            %li= msg
    .field
      = f.label :name, :autofocus => 'autofocus'
      = f.text_field :name
      %br/
      = f.label :occasion
      = f.text_field :occasion
      %br/
      = f.label :notes
      = f.text_field :notes
      %br/
      - Piece.order(:image).each do |piece|
        .outfit_item
          = image_tag(piece.image, :size => "100x100", :class => 'select_piece')
          = check_box_tag 'outfit[piece_ids][]', piece.id, piece.in?(@outfit.pieces), :id => nil, :class => 'outfit_checkbox'
    .actions
      = f.submit

app/views/outfits/_oldform.html.erb
<%= form_for(@outfit) do |f| %>
  <% if @outfit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outfit.errors.count, "error") %> prohibited this outfit from being saved:</h2>

      <ul>
      <% @outfit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, :autofocus => 'autofocus' %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :occasion %>
    <%= f.text_field :occasion %>
    <br>
    <%= f.label :notes %>
    <%= f.text_field :notes %>

<br>
<% Piece.order(:image).each do |piece| %>
  <span><%= image_tag(piece.image, :size => "100x100") %>
  <%= check_box_tag 'outfit[piece_ids][]', piece.id, piece.in?(@outfit.pieces) %></span>
<% end %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outfits/edit.html.erb
<h1>Editing outfit</h1>

<%= render 'form' %>

<%= link_to 'Show', @outfit %> |
<%= link_to 'Back', outfits_path %>

app/views/outfits/index.html.erb
<div class="outfit_display">

<% @outfits.each do |outfit| %>
<%= link_to(outfit.name, outfit) %>
<br>
<br>

  <% outfit.pieces.each do |piece| %>
  <%= image_tag(piece.image, :size => "200x200") %>
 <% end %>
<br>
<br>
<br>
<% end %>
</div>


<%= link_to('New Outfit', new_outfit_path) %>

app/views/outfits/index.html.haml
.outfit_display
  - @outfits.each do |outfit|
    #{link_to(outfit.name, outfit)}
    %br/
    %br/
    - outfit.pieces.each do |piece|
      = image_tag(piece.image, :size => "200x200")

    %br/
    %br/
    %br/

app/views/outfits/indexold.html.erb
<div class="page_headers">Greatest Hits</div>
<br>
<br>
<br>
<%= link_to 'New Outfit', new_outfit_path %>

<div class="row">

  <!-- Side Bar -->

<div class="four mobile-four columns">

          <img src="http://1.bp.blogspot.com/_0r0x8pliuno/TTiIDWOREZI/AAAAAAAAAOg/lKYr5zaj-_k/s1600/tumblr_lfc0ie97EH1qg7zeko1_500.png">

          <div class="hide-for-small panel">
            <h3>Browse your outfits</h3>
            <h5 class="subheader">Greatest hits
            </h5>
          </div>

          <a href="#">
          <div class="panel callout radius" align="center">
            <h6>99&nbsp; piecess in your closet</h6>
          </div>
          </a>

        </div>

    <!-- End Side Bar -->
<!--
Trial Code
 -->
<%= link_to('New Outfit', new_outfit_path) %>

:: <%= link_to('Edit Outfit', edit_outfit_path(@outfit)) %>
:: <%= link_to('Delete Outfit', @outfit, :method => :delete, :confirm => 'Are you sure?') %>

<div class='spacer'></div>

<ul>
  <li><%= @outfit.name %></li>
  <li><%= image_tag(@outfit.image) %></li>

  <% @outfit.pieces.each do |piece| %>
    <li><%= piece.item %></li>
    <li><%= image_tag(piece.image) %></li>
  <% end %>
</ul>
<!--
End Trial Code

 -->
 <!-- Thumbnails -->

        <div class="eight columns">
          <div class="row">

<% @outfits.each do |outfit| %>

<div class="four mobile-two columns">

  <%=outfit.name %><p>



    <!-- End Thumbnails -->

<% end %>

</table>

<br />

app/views/outfits/new.html.erb
<div class="page_headers">New outfit</div>
<br>
<br>
<br>
<%= render 'form' %>

<%= link_to 'Back', outfits_path %>

app/views/outfits/new.html.haml
.page_headers New outfit
%br/
%br/
%br/
/ #myModal.reveal-modal
/   %h2 Awesome. I have it.
/   %p.lead Your couch.  It is mine.
/   %p Im a cool paragraph that lives inside of an even cooler modal. Wins
/   %a.close-reveal-modal ×

/   %a{"data-reveal-id" => "myModal", :href => "#"} Click Me For A Modal
= render 'form'
= link_to 'Back', outfits_path, :class => 'links'

app/views/outfits/oldindex.html.erb
<div class="outfit_display">

<% @outfits.each do |outfit| %>
<%= link_to(outfit.name, outfit) %>
<br>
<br>

  <% outfit.pieces.each do |piece| %>
  <%= image_tag(piece.image, :size => "200x200") %>
 <% end %>
<br>
<br>
<br>
<% end %>
</div>

app/views/outfits/oldnew.html.erb
<div class="page_headers">New outfit</div>
<br>
<br>
<br>
<%= render 'form' %>

<%= link_to 'Back', outfits_path %>

app/views/outfits/oldshow.html.erb
<p id="notice"><%= notice %></p>

<p>
<div class="outfit_name"><%= @outfit.name %></div>
<br>
<br>
<div class="outfit_display"
  <% @outfit.pieces.each do |piece| %>
    <div class="outfit_display"><%= image_tag(piece.image, :size => "250x250") %></div>
  <% end %>
</div>
</ul>

</p>

<%= link_to('New Outfit', new_outfit_path) %>
| <%= link_to 'Edit', edit_outfit_path(@outfit) %>
| <%= link_to('Delete Outfit', @outfit, :method => :delete, :confirm => 'Are you sure?') %>




<!--

<%= link_to('Go to Piece', piece_path) %> -->

app/views/outfits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<div class="outfit_name"><%= @outfit.name %></div>
<br>
<br>
<div class="outfit_display"
  <% @outfit.pieces.each do |piece| %>
    <div class="outfit_display"><%= image_tag(piece.image, :size => "250x250") %></div>
  <% end %>
</div>
</ul>

</p>

<%= link_to('New Outfit', new_outfit_path) %>
| <%= link_to 'Edit', edit_outfit_path(@outfit) %>
| <%= link_to('Delete Outfit', @outfit, :method => :delete, :confirm => 'Are you sure?') %>




<!--

<%= link_to('Go to Piece', piece_path) %> -->

app/views/outfits/show.html.haml
%p#notice= notice
%p
  .outfit_name= @outfit.name
  %br/
  %br/
  <div class="outfit_display"
  - @outfit.pieces.each do |piece|
    .outfit_display= image_tag(piece.image, :size => "250x250")
.links
  = link_to('New Outfit', new_outfit_path)
  | #{link_to 'Edit', edit_outfit_path(@outfit)}
  | #{link_to('Delete Outfit', @outfit, :method => :delete, :confirm => 'Are you sure?')}
  /


  / <haml:loud> link_to('Go to Piece', piece_path) </haml:loud>