config/routes.rb
Style::Application.routes.draw do

  root :to => 'home#index'

  resources :outfits_pieces
  resources :outfits
  resources :pieces
  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # resources :home
  # get '/about' => 'home#about'
  # get '/faq' => 'home#faq'
  # get '/contact' => 'home#contact'
  # get '/index' => 'home#index'
end

app/models/piece.rb
# == Schema Information
#
# Table name: pieces
#
#  id         :integer          not null, primary key
#  image      :text
#  item       :string(255)
#  designer   :string(255)
#  color      :string(255)
#  material   :string(255)
#  fit        :string(255)
#  size       :string(255)
#  details    :text
#  notes      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Piece < ActiveRecord::Base
  attr_accessible :image, :item, :designer, :color, :material, :fit, :size, :details, :notes
  has_and_belongs_to_many :outfits
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  # GET /pieces
  # GET /pieces.json

  def index
    @pieces = Piece.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pieces }

    # @pieces = @auth.pieces.order(:item)
    # @items = @auth.pieces.map(&:item).uniq.sort
    end
  end

  # GET /pieces/1
  # GET /pieces/1.json
  def show
    @piece = Piece.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @piece }
    end
  end

  # GET /pieces/new
  # GET /pieces/new.json
  def new
    @piece = Piece.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @piece }
    end
  end

  # GET /pieces/1/edit
  def edit
    @piece = Piece.find(params[:id])
  end

  # POST /pieces
  # POST /pieces.json
  def create
    @piece = Piece.new(params[:piece])

    respond_to do |format|
      if @piece.save
        format.html { redirect_to @piece, notice: 'Piece was successfully created.' }
        format.json { render json: @piece, status: :created, location: @piece }
      else
        format.html { render action: "new" }
        format.json { render json: @piece.errors, status: :unprocessable_entity }

    # @auth.pieces << Piece.create(params[:piece])
    # @pieces = @auth.pieces.order(:item)
    # @pieces = @auth.pieces.map(&:item).uniq.sort
      end
    end
  end

  # PUT /pieces/1
  # PUT /pieces/1.json
  def update
    @piece = Piece.find(params[:id])

    respond_to do |format|
      if @piece.update_attributes(params[:piece])
        format.html { redirect_to @piece, notice: 'Piece was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pieces/1
  # DELETE /pieces/1.json
  def destroy
    @piece = Piece.find(params[:id])
    @piece.destroy

    respond_to do |format|
      format.html { redirect_to pieces_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/pieces/_form.html.erb
<%= form_for(@piece) do |f| %>
  <% if @piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@piece.errors.count, "error") %> prohibited this piece from being saved:</h2>

      <ul>
      <% @piece.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :image, :autofocus => 'autofocus'  %>
    <%= f.text_field :image %>
    <br>
    <%= f.label :item %>
    <%= f.text_field :item %>
    <br>
    <%= f.label :designer %>
    <%= f.text_field :designer %>
    <br>
    <%= f.label :color %>
    <%= f.text_field :color %>
    <br>
    <%= f.label :material %>
    <%= f.text_field :material %>
    <br>
    <%= f.label :fit %>
    <%= f.text_field :fit %>
    <br>
    <%= f.label :size %>
    <%= f.text_field :size %>
    <br>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <br>
    <%= f.label :notes %>
    <%= f.text_field :notes %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pieces/edit.html.erb
<h1>Edit This Piece</h1>

<%= render 'form' %>

<%= link_to 'Show', @piece %> |
<%= link_to 'Back', pieces_path %>

app/views/pieces/index.html.erb
<h1>Your Closet</h1>

<div class="row">

  <!-- Side Bar -->

<div class="four mobile-four columns">

          <img src="http://1.bp.blogspot.com/_0r0x8pliuno/TTiIDWOREZI/AAAAAAAAAOg/lKYr5zaj-_k/s1600/tumblr_lfc0ie97EH1qg7zeko1_500.png">

          <div class="hide-for-small panel">
            <h3>Browse your wardrobe</h3>
            <h5 class="subheader">Go shopping in your closet!
            </h5>
          </div>

        </div>

    <!-- End Side Bar -->

 <!-- Thumbnails -->

        <div class="eight columns">
          <div class="row">

<% @pieces.each do |piece| %>

<div class="four mobile-two columns">

              <%= link_to(image_tag(piece.image), piece) %>
<!--
              <div class="panel">
                <h5><%= piece.item %></h5>
                <h6 class="subheader"><%= piece.designer %></h6>
              </div> -->
            </div>
<br>
<br>

    <!-- End Thumbnails -->
<!--


    <td><%= link_to 'Show', piece %></td>
    <td><%= link_to 'Edit', edit_piece_path(piece) %></td>
    <td><%= link_to 'Destroy', piece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr> -->

<% end %>

</table>

<br />

app/views/pieces/index.html.haml
#your_closet_page_header Your Closet
.row
  / Side Bar
  .four.mobile-four.columns
    %img{:src => "http://1.bp.blogspot.com/_0r0x8pliuno/TTiIDWOREZI/AAAAAAAAAOg/lKYr5zaj-_k/s1600/tumblr_lfc0ie97EH1qg7zeko1_500.png"}/
    .hide-for-small.panel
      %h3 Browse your wardrobe
      %h5.subheader
        Go shopping in your closet!
  / End Side Bar
  / Thumbnails

  .eight.columns
    .row
      - @pieces.each do |piece|
        .four.mobile-two.columns
          = link_to(image_tag(piece.image), piece, :class => 'pretty_pictures', :size => "100x100")
          /
            <div class="panel">
            <h5><haml:loud> piece.item </haml:loud></h5>
            <h6 class="subheader"><haml:loud> piece.designer </haml:loud></h6>
            </div>
        %br/
        %br/
        / End Thumbnails
        /
          <td><haml:loud> link_to 'Show', piece </haml:loud></td>
          <td><haml:loud> link_to 'Edit', edit_piece_path(piece) </haml:loud></td>
          <td><haml:loud> link_to 'Destroy', piece, method: :delete, data: { confirm: 'Are you sure?' } </haml:loud></td>
          </tr>
      %br/

app/views/pieces/new.html.erb
<div class="page_headers">New piece</div>
<br>
<br>
<br>
<div class="new_piece_display">

<%= render "form" %></div>

<div id="form_image">
<img src="http://cdn.kirnazabete.com/media/catalog/product/cache/1/image/5e06319eda06f020e43594a9c230972d/p/i/pia27pnanblk_1/KirnaZabete-Piamita-Nan-Pajama-Pant-31.jpg"></div>


<%= link_to 'Back', pieces_path %>

app/views/pieces/new.html.haml
.page_headers New piece
%br/
%br/
%br/
.new_piece_display
  = render "form"
#form_image
  %img{:src => "http://cdn.kirnazabete.com/media/catalog/product/cache/1/image/5e06319eda06f020e43594a9c230972d/p/i/pia27pnanblk_1/KirnaZabete-Piamita-Nan-Pajama-Pant-31.jpg"}/
  / = link_to 'Back', pieces_path

app/views/pieces/oldindex.html.erb
<h1>Your Closet</h1>

<div class="row">

  <!-- Side Bar -->

<div class="four mobile-four columns">

          <img src="http://1.bp.blogspot.com/_0r0x8pliuno/TTiIDWOREZI/AAAAAAAAAOg/lKYr5zaj-_k/s1600/tumblr_lfc0ie97EH1qg7zeko1_500.png">

          <div class="hide-for-small panel">
            <h3>Browse your wardrobe</h3>
            <h5 class="subheader">Go shopping in your closet!
            </h5>
          </div>

        </div>

    <!-- End Side Bar -->

 <!-- Thumbnails -->

        <div class="eight columns">
          <div class="row">

<% @pieces.each do |piece| %>

<div class="four mobile-two columns">

              <%= link_to(image_tag(piece.image), piece, :size => "100x100") %>
<!--
              <div class="panel">
                <h5><%= piece.item %></h5>
                <h6 class="subheader"><%= piece.designer %></h6>
              </div> -->
            </div>
<br>
<br>

    <!-- End Thumbnails -->
<!--


    <td><%= link_to 'Show', piece %></td>
    <td><%= link_to 'Edit', edit_piece_path(piece) %></td>
    <td><%= link_to 'Destroy', piece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr> -->

<% end %>

</table>

<br />

app/views/pieces/oldnew.html.erb
<div class="page_headers">New piece</div>
<br>
<br>
<br>
<div class="new_piece_display">

<%= render "form" %></div>

<div id="form_image">
<img src="http://cdn.kirnazabete.com/media/catalog/product/cache/1/image/5e06319eda06f020e43594a9c230972d/p/i/pia27pnanblk_1/KirnaZabete-Piamita-Nan-Pajama-Pant-31.jpg"></div>

<!--
<%= link_to 'Back', pieces_path %>
 -->

app/views/pieces/show.html.erb
<p id="notice"><%= notice %></p>

<p class="piece_display">

  <br>
  <b><%= @piece.item %> by <%= @piece.designer %></b>
  <br>
  <br>
  <label class="piece_labels">Color: <%= @piece.color %></label>
  <br>
  <label class="piece_labels">Material: <%= @piece.material %></label>
  <br>
  <label class="piece_labels">Fit: <%= @piece.fit %></label>
  <br>
  <label class="piece_labels">Size: </label><%= @piece.size %>
  <br>
  <label class="piece_labels">Details: <%= @piece.details %>
  <br></label>
  <label class="piece_labels">Notes: <%= @piece.notes %>
  <br></label>
  <br>
  <%= link_to 'Edit', edit_piece_path(@piece) %> |
  <%= link_to('Delete', @piece, :method => :delete, :confirm => 'Are you sure?') %> |
  <%= link_to 'Back', pieces_path %>
  <div id="piece_image_display">
    <%= image_tag(@piece.image) %>
  </div>
</p>

app/views/pieces/show.html.haml
%p#notice= notice
%p.piece_display
  %br/
  %b
    = @piece.item, :class => 'piece'
    by #{@piece.designer}
  %br/
  %br/
  %label.piece_labels
    Color: #{@piece.color}
  %br/
  %label.piece_labels
    Material: #{@piece.material}
  %br/
  %label.piece_labels
    Fit: #{@piece.fit}
  %br/
  %label.piece_labels Size:
  = @piece.size
  %br/
  %label.piece_labels
    Details: #{@piece.details}
    %br/
  %label.piece_labels
    Notes: #{@piece.notes}
    %br/
  %br/
  = link_to 'Edit', edit_piece_path(@piece)
  = link_to('Delete', @piece, :method => :delete, :confirm => 'Are you sure?')
  = link_to 'Back', pieces_path
  #piece_image_display
    = image_tag(@piece.image)