config/routes.rb
Style::Application.routes.draw do

  root :to => 'home#index'

  resources :outfits_pieces
  resources :outfits
  resources :pieces
  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # resources :home
  # get '/about' => 'home#about'
  # get '/faq' => 'home#faq'
  # get '/contact' => 'home#contact'
  # get '/index' => 'home#index'
end

app/models/outfits_pieces.rb
# == Schema Information
#
# Table name: outfits_pieces
#
#  piece_id  :integer
#  outfit_id :integer
#

class OutfitsPieces < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/outfits_pieces_controller.rb
class OutfitsPiecesController < ApplicationController
  # GET /outfits_pieces
  # GET /outfits_pieces.json
  def index
    @outfits_pieces = OutfitsPiece.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @outfits_pieces }
    end
  end

  # GET /outfits_pieces/1
  # GET /outfits_pieces/1.json
  def show
    @outfits_piece = OutfitsPiece.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @outfits_piece }
    end
  end

  # GET /outfits_pieces/new
  # GET /outfits_pieces/new.json
  def new
    @outfits_piece = OutfitsPiece.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @outfits_piece }
    end
  end

  # GET /outfits_pieces/1/edit
  def edit
    @outfits_piece = OutfitsPiece.find(params[:id])
  end

  # POST /outfits_pieces
  # POST /outfits_pieces.json
  def create
    @outfits_piece = OutfitsPiece.new(params[:outfits_piece])

    respond_to do |format|
      if @outfits_piece.save
        format.html { redirect_to @outfits_piece, notice: 'Outfits piece was successfully created.' }
        format.json { render json: @outfits_piece, status: :created, location: @outfits_piece }
      else
        format.html { render action: "new" }
        format.json { render json: @outfits_piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /outfits_pieces/1
  # PUT /outfits_pieces/1.json
  def update
    @outfits_piece = OutfitsPiece.find(params[:id])

    respond_to do |format|
      if @outfits_piece.update_attributes(params[:outfits_piece])
        format.html { redirect_to @outfits_piece, notice: 'Outfits piece was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @outfits_piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outfits_pieces/1
  # DELETE /outfits_pieces/1.json
  def destroy
    @outfits_piece = OutfitsPiece.find(params[:id])
    @outfits_piece.destroy

    respond_to do |format|
      format.html { redirect_to outfits_pieces_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/outfits_pieces_helper.rb
module OutfitsPiecesHelper
end

app/views/outfits_pieces/_form.html.erb
<%= form_for(@outfits_piece) do |f| %>
  <% if @outfits_piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outfits_piece.errors.count, "error") %> prohibited this outfits_piece from being saved:</h2>

      <ul>
      <% @outfits_piece.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outfits_pieces/edit.html.erb
<h1>Editing outfits_piece</h1>

<%= render 'form' %>

<%= link_to 'Show', @outfits_piece %> |
<%= link_to 'Back', outfits_pieces_path %>

app/views/outfits_pieces/index.html.erb
<h1>Listing outfits_pieces</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outfits_pieces.each do |outfits_piece| %>
  <tr>
    <td><%= outfits_piece.name %></td>
    <td><%= link_to 'Show', outfits_piece %></td>
    <td><%= link_to 'Edit', edit_outfits_piece_path(outfits_piece) %></td>
    <td><%= link_to 'Destroy', outfits_piece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Outfits piece', new_outfits_piece_path %>

app/views/outfits_pieces/new.html.erb
<h1>New outfits_piece</h1>

<%= render 'form' %>

<%= link_to 'Back', outfits_pieces_path %>

app/views/outfits_pieces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @outfits_piece.name %>
</p>


<%= link_to 'Edit', edit_outfits_piece_path(@outfits_piece) %> |
<%= link_to 'Back', outfits_pieces_path %>