config/routes.rb
Style::Application.routes.draw do

  root :to => 'home#index'

  resources :outfits_pieces
  resources :outfits
  resources :pieces
  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # resources :home
  # get '/about' => 'home#about'
  # get '/faq' => 'home#faq'
  # get '/contact' => 'home#contact'
  # get '/index' => 'home#index'
end

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="twelve columns"><hr />
    <div class="row">

      <div class="six columns">
        <p>&copy; Stylemine 2013</p>
      </div>

      <div class="six columns">
        <ul class="link-list right">
          <li><a href="/about">About</a></li>
          <li><a href="/faq">FAQ</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>
      </div>

    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="row">
    <div class="twelve columns">

    <nav class="top-bar">
      <ul class="top-bar">
        <li class="name"><h1><a href="/">Stylemine</a></h1></li>
        <li class="toggle-topbar"><a href="#"></a></li>
      </ul>

      <section>
        <ul class="left">
          <li><%= link_to 'Open Your Closet', pieces_path %></li>
          <li><%= link_to 'Browse Outfits', outfits_path %></li>
          <li><%= link_to 'Add Piece', new_piece_path %></li>
          <li><%= link_to 'Create Outfit', new_outfit_path %>
          <li><%= link_to 'Create Account', new_user_path %>
          </li>

        </ul>

      <%= login_nav %>

      </section>
    </nav>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>Stylemine</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="stylesheets/foundation.css">
  -->

  <!-- Included CSS Files (Compressed) -->
<!--
  <link rel="stylesheet" href="stylesheets/foundation.min.css">
  <link rel="stylesheet" href="stylesheets/app.css">

  <script src="javascripts/modernizr.foundation.js"></script>
   -->
</head>
<body>
  <div class="row">
    <div class="twelve columns">

    <!-- Navigation -->

      <div class="row">
        <div class="twelve columns">

        <nav class="top-bar">
          <ul class="top-bar">
            <li class="name"><h1><a href="/home">Stylemine</a></h1></li>
            <li class="toggle-topbar"><a href="#"></a></li>
          </ul>

          <section>
            <ul class="left">
              <li><a href="/pieces">Open Your Closet</a></li>
              <li><a href="/outfits">Browse Outfits</a></li>
              <li><%= link_to 'Add Piece', new_piece_path %></li>
              <li><%= link_to 'Create Outfit', new_outfit_path %></li>
            </ul>

          </section>
        </nav>

      </div>
    </div>

    <!-- End Navigation -->

 <section><%= yield %></section>

          </div>
        </div>
      </div>


    <!-- Footer -->

      <footer class="row">
        <div class="twelve columns"><hr />
          <div class="row">

            <div class="six columns">
              <p>&copy; Stylemine 2013</p>
            </div>

            <div class="six columns">
              <ul class="link-list right">
                <li><a href="/about">About</a></li>
                <li><a href="#">FAQ</a></li>
                <li><a href="#">Contact Us</a></li>
              </ul>
            </div>

          </div>
        </div>
      </footer>

    <!-- End Footer -->

    </div>
  </div>

  <!-- Included JS Files (Uncompressed) -->
  <!--

  <script src="javascripts/jquery.js"></script>

  <script src="javascripts/jquery.foundation.mediaQueryToggle.js"></script>

  <script src="javascripts/jquery.foundation.forms.js"></script>

  <script src="javascripts/jquery.event.move.js"></script>

  <script src="javascripts/jquery.event.swipe.js"></script>

  <script src="javascripts/jquery.foundation.reveal.js"></script>

  <script src="javascripts/jquery.foundation.orbit.js"></script>

  <script src="javascripts/jquery.foundation.navigation.js"></script>

  <script src="javascripts/jquery.foundation.buttons.js"></script>

  <script src="javascripts/jquery.foundation.tabs.js"></script>

  <script src="javascripts/jquery.foundation.tooltips.js"></script>

  <script src="javascripts/jquery.foundation.accordion.js"></script>

  <script src="javascripts/jquery.placeholder.js"></script>

  <script src="javascripts/jquery.foundation.alerts.js"></script>

  <script src="javascripts/jquery.foundation.topbar.js"></script>

  <script src="javascripts/jquery.foundation.joyride.js"></script>

  <script src="javascripts/jquery.foundation.clearing.js"></script>

  <script src="javascripts/jquery.foundation.magellan.js"></script>

  -->

  <!-- Included JS Files (Compressed) -->
<!--

  <script src="javascripts/jquery.js"></script>
  <script src="javascripts/foundation.min.js"></script>
 -->

  <!-- Initialize JS Plugins -->
  <script src="javascripts/app.js"></script>
</body>
</html>

app/views/layouts/homepage.html.erb
<!-- First Band (Slider) -->
  <!-- The Orbit slider is initialized at the bottom of the page by calling .orbit() on #slider -->

<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>Stylemine</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>

<body>

<%= render :partial => 'layouts/nav' %>

<div id="main_heading">

<center>Stylemine</center>
</div>
<br>
<br>
<br>

  <div class="row">
    <div class="twelve columns">
      <div id="slider">
        <img src="http://www.fashion156.com/resources/uploads/2012/09/Fashion156-Kinder-Aggugini-Runway-6.jpg" />
        <img src="http://www.fashion156.com/resources/uploads/2012/09/marcaitkennovachiu2.jpg" />
        <img src="http://www.fashion156.com/resources/uploads/2012/09/fashion156-damir-doma-2.jpg" />
        <img src="http://www.fashion156.com/resources/uploads/2012/09/fashion156roksandailinic2.jpg" />
      </div>

      <hr />
    </div>
  </div>

<br>
<br>
<br>

  <!-- Three-up Content Blocks -->

  <div class="row">

    <div class="four columns">
      <img src="http://cdn.kirnazabete.com/media/catalog/product/cache/1/image/5e06319eda06f020e43594a9c230972d/e/r/erd27p88dmul_1/.jpg" />
      <h4>Browse Your Closet</h4>

      <p>In a style rut?  Check out what you already have and go shopping in your closet!  Use this feature to stay organized and inspire you to get creative.</p>
    </div>

    <div class="four columns">
      <img src="http://cdn.kirnazabete.com/media/catalog/product/cache/1/image/5e06319eda06f020e43594a9c230972d/c/o/co26rdolbur_1/.jpg" />
      <h4>Create a Look</h4>
      <p>Put together an outfit for an event, create a new look from old clothes, or pack a suitcase the smart way. Get a second opinion from a friend before you go out!</p>
    </div>

    <div class="four columns">
      <img src="http://cdn.kirnazabete.com/media/catalog/product/cache/1/image/5e06319eda06f020e43594a9c230972d/k/w/kw27p118ylw_1/.jpg" />
      <h4>Try on Something New.</h4>
      <p>See how something works with your wardrobe!  Add a photo from online or your phone, mix and match with what's already in your closet, and decide whether or not to buy.</p>
    </div>

  </div>

<script type="text/javascript">
     $(window).load(function() {
         $('#slider').orbit();
     });
  </script>

</body>
</html>

app/views/layouts/pieces_layout.html.erb
 <!-- Thumbnails -->

        <div class="eight columns">
          <div class="row">

            <div class="four mobile-two columns">
              <img src="http://placehold.it/1000x1000&text=Thumbnail">

              <div class="panel">
                <h5>Item Name</h5>
                <h6 class="subheader">$000.00</h6>
              </div>
            </div>

            <div class="four mobile-two columns">
              <img src="http://placehold.it/500x500&text=Thumbnail">

              <div class="panel">
                <h5>Item Name</h5>
                <h6 class="subheader">$000.00</h6>
              </div>
            </div>

            <div class="four mobile-two columns">
              <img src="http://placehold.it/500x500&text=Thumbnail">

              <div class="panel">
                <h5>Item Name</h5>
                <h6 class="subheader">$000.00</h6>
              </div>
            </div>

            <div class="four mobile-two columns">
              <img src="http://placehold.it/500x500&text=Thumbnail">

              <div class="panel">
                <h5>Item Name</h5>
                <h6 class="subheader">$000.00</h6>
              </div>
            </div>

            <div class="four mobile-two columns">
              <img src="http://placehold.it/500x500&text=Thumbnail">

              <div class="panel">
                <h5>Item Name</h5>
                <h6 class="subheader">$000.00</h6>
              </div>
            </div>

            <div class="four mobile-two columns">
              <img src="http://placehold.it/500x500&text=Thumbnail">

              <div class="panel">
                <h5>Item Name</h5>
                <h6 class="subheader">$000.00</h6>
              </div>
            </div>

    <!-- End Thumbnails -->